### ISSUE TITLE
Running bot.py and it says no module named 'requests'

### ISSUE THREAD

**Issue by kk1775** [raghavpatnecha/smartmirror#13]
I follow the steps on hh and when I execute the bot.py and it said no module named 'requests'
I run python bot.py and I get this:
Traceback (most recent call last):
File "bot.py", line 7, in 
import requests
ModuleNotFoundError: No module named 'requests'
What's the problem? I'm using Win10.
Can someone please tell me how to solve this?

**Comment by akshaybahadur21** [comment]
From a cmd prompt, use > Path\easy_install.exe requests, where Path is your Python*\Scripts folder, if it was installed. (For example: C:\Python32\Scripts\easy_install.exe)

If you don't have easy install and are running on a windows machine, you can get it here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#distribute

If you manually want to add a library to a windows machine, you can download the compressed library, uncompress it, and then place it into the Lib folder of your python path. (For example: C:\Python27\Lib)

**Comment by kk1775** [comment]
I do as you said and I use both ways by the easy install and the manual steps to install the library requests. 
But it still shows the same error message.
Is there another factor that causes this?
BTW, what kind of OS did you run? Cause I would like to try this on raspberry pi 3 in the future.
Thanks a lot.

**Comment by kk1775** [comment]
Hi, I found it was the problem on the path of the different version of Python.
Yet, I still can't run the bot.py sadly. It shows this:
Error: Could not find or load main class Py4JServer
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "C:\Users\kk1775\Desktop\AI-Smart-Mirror-master\nlg.py", line 7, in <module>
    gateway = launch_py4j_server()
  File "C:\Users\kk1775\Desktop\AI-Smart-Mirror-master\py4j_server\__init__.py", line 34, in launch_py4j_server
    _port = int(_pid.stdout.readline())
ValueError: invalid literal for int() with base 10: ' '
What should I do? plz help I really apreciate.

**Comment by akshaybahadur21** [comment]
This code doesnt work on windows.
There is a workaround for that but that is not a part of this code.
Kindly use Vbox for running it on ubuntu

**Comment by iggytree** [comment]
hey whats the work around on windows by any chance?

**Comment by aak2003** [comment]
Try with virtual box

**Comment by aak2003** [comment]
Try installing py4j for your system

**Comment by aak2003** [comment]
Sudo apt-get install requests , pip install requests.

**Comment by PoojaAmin29** [comment]
I am also getting the same error and i am doing it in raspberry pi itself, i tried out these commands
sudo apt-get install requests 
pip install requests.
but it shows pip requests already installed but when i run python bot.py again it gives the same error

**Comment by akshaybahadur21** [comment]
@PoojaAmin29 - Can you share the stack trace?
