### ISSUE TITLE
not recognising speech or talkback

### ISSUE THREAD

**Issue by rachnov55** [raghavpatnecha/smartmirror#16]
so after finally managing to install everything, I get this error on starting the bot.py script

```
/usr/local/lib/python2.7/dist-packages/pydub/utils.py:178: RuntimeWarning: Couldn't find ffplay or avplay - defaulting to ffplay, but may not work
  warn("Couldn't find ffplay or avplay - defaulting to ffplay, but may not work", RuntimeWarning)
Warning: OpenCV not installed. To use facial recognition, make sure you've properly configured OpenCV.
Found face
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
  File "bot.py", line 522, in <module>
    bot.start()
  File "bot.py", line 50, in start
    recognizer, audio = self.speech.listen_for_audio()
  File "/home/pi/smartmirror/speech.py", line 33, in listen_for_audio
    m = sr.Microphone()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 86, in __init__
    device_info = audio.get_device_info_by_index(device_index) if device_index is not None else audio.get_default_input_device_info()
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 949, in get_default_input_device_info
    device_index = pa.get_default_input_device()
IOError: No Default Input Device Available

```

I'm using a soundblaster play 3 USB dongle for mic and speakers, and it works for my other installation of an assistant module, but I have no idea how to make it work here.

weird thing was I managed to run it once, where it was just listening, but kept saying speech recognition does not uinderstand audio.  then i rebooted and i can't et it to work anymore

**Comment by rachnov55** [comment]
ok so now it's listening to me, but there's no feedback 

```
oogle Speech Recognition could not understand audio
Found face
I'm listening
Found audio
Google Speech Recognition thinks you said what song is this
Found face
I'm listening
Found audio
Google Speech Recognition could not understand audio
Found face
I'm listening
Found audio
Google Speech Recognition thinks you said what time is it
Found face
I'm listening
Found audio
Google Speech Recognition could not understand audio
Found face
I'm listening
```

**Comment by aak2003** [comment]
Is NVM launched?

**Comment by aak2003** [comment]
Sry npm

**Comment by rachnov55** [comment]
You mean npm start the magic mirror? Yes it’s launched

After launching I opened another terminal to start python bot.py

It seems to not be registering my api client

Sent from Mail for Windows 10

**Comment by aak2003** [comment]
Try connecting it to another network for internet

**Comment by rachnov55** [comment]
now i'm getting this again even though I have google api python client installed.

does it need to be in the hhsmartmirror directory? caus I don't see it in there

```
aceback (most recent call last):
  File "bot.py", line 13, in <module>
    from apiclient.discovery import build
ImportError: No module named apiclient.discovery
```

**Comment by aak2003** [comment]
It might need it because we enter the code that activates virtual
environment in the hhsmartmirror folder

Also try rebooting the pi and try starting it  , if it still doesn't start
I recommend to reboot and start it 2-3 times.
Because I have done the hhsmartmirror project and whenever it didn't work I
rebooted the pi, cause I also had the same problem

**Comment by rachnov55** [comment]
Well I can’t for the life of me figure out how to get it in the hhsmartmirror folder…I can’t copy it over, and I can’t install it in there

Sent from Mail for Windows 10

**Comment by aak2003** [comment]
If you live in India please share your phone number for ease of discussion
If out of India o will call through WhatsApp so please share mobile details
if you are comfortable.

**Comment by rachnov55** [comment]
Thanks! 

As of now I’ve figured out how to get the api client installed in hhsmartmirror → just adding google-api-python-client into the list in requirements.txt

But now it’s giving me the “I’m listening” “found sound” “Google speech recognition does not understand…” again

I’ll keep trying so I don’t have to trouble you with every single little problem I run into.

If I’m really stuck I’ll take up your offer for a call 😊 I live in Singapore btw.

And will you allow me to send a small donation if you have a paypal acc or something

Sent from Mail for Windows 10

**Comment by aak2003** [comment]
Thanks btw
And the code for hhsmartmirror virtual environment is 1. Git clone the
hhsmartmirror folder
2. Have virtual environment installed
3. Run source hhsmartmirror/bin/activate

Btw my PayPal account email is dudejunior12345@gmail.com

And my mobile is +91 7010972696

Btw if you don't mind may I know your age?

**Comment by aak2003** [comment]
And my name is Aakaash

**Comment by rachnov55** [comment]
My name is Albert and I’m 40.

I’m sorry for all the questions…I’m really new to this…I should go take some courses on computer language and scripting

Is there any file I need to edit so that the AI knows which source for audio/mic input?

Sent from Mail for Windows 10

**Comment by aak2003** [comment]
Check for your system settings on your device and select the input/output
mode.

Btw I'm 14 and I am doing a bit of coding and computing from 3 years. Wish
you good luck for your future projects and this one.

**Comment by rachnov55** [comment]
Did u do this on a raspberry pi?  I’ve managed to get it to recognize voice input, but I still hear no sound feedback.  I read online that it runs really slowly for raspberry pi.  Also, I’m on a pretty fast internet 100mbps connection so I doubt it’s my network.

Sent from Mail for Windows 10

**Comment by aak2003** [comment]
Yes on raspberry pi 3b

**Comment by rachnov55** [comment]
Sighs I have no idea what to do then haha

Sent from Mail for Windows 10

**Comment by aak2003** [comment]
Check if ffmpeg is installed properly

**Comment by aak2003** [comment]
Cause that's the dependency files for the whole project

**Comment by aak2003** [comment]
I have recently started my YouTube channel called Hacker Paracosm in which
I am going to make videos about coding and building and computing
tutorials. Link to my channel

https://m.youtube.com/channel/UCoTUo0QJJdm4vDgF3f7f5bg

**Comment by rachnov55** [comment]
While reinstalling, during the “brew install gcc” procedure I’m running into a lot of these errors →

In file included from ./tm.h:23:0,
                 from ../../gcc/c-family/c-gimplify.c:29:
../../gcc/config/elfos.h:102:21: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
    fprintf ((FILE), "%s"HOST_WIDE_INT_PRINT_UNSIGNED"\n",\

does this affect the installation of brew or ffmpeg?

Sent from Mail for Windows 10

**Comment by rachnov55** [comment]
Is gcc necessary? I just spent over an hr trying to install it only to get this

Error: gcc 5.5.0 did not build
Logs:
     /home/pi/.cache/Homebrew/Logs/gcc/02.make
     /home/pi/.cache/Homebrew/Logs/gcc/01.configure.cc
     /home/pi/.cache/Homebrew/Logs/gcc/01.configure
     /home/pi/.cache/Homebrew/Logs/gcc/02.make.cc
     /home/pi/.cache/Homebrew/Logs/gcc/00.options.out
READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

Sent from Mail for Windows 10

**Comment by aak2003** [comment]
No gcc isn't important.

Gcc has completely different dependency files than ffmpeg.

The dependency files of gcc has nothing to do with this project.

**Comment by aak2003** [comment]
Are the magic mirror folders and the folders of this GitHub project
properly pasted in the hhsmartmirror folder?

**Comment by aak2003** [comment]
Also try with a different mic

**Comment by rachnov55** [comment]
How do I paste the folders in the hhsmartmirror folder?

Sent from Mail for Windows 10

**Comment by aak2003** [comment]
Refer the 1st 10 mins of the hacker house smartmirror video and view the
readme.dm file of this GitHub project.

**Comment by rachnov55** [comment]
Oh ok I’ve done all that…I thought you meant copy to the virtual environment

Sent from Mail for Windows 10

**Comment by aak2003** [comment]
Ok

**Comment by aak2003** [comment]
Did you check if virtual environment is getting activated between all three
folders?

**Comment by aak2003** [comment]
That means that all the required files of the three folders are
interconnected with each other when virtual environment is running.

**Comment by rachnov55** [comment]
How do I check that?


Sent from Mail for Windows 10

**Comment by rachnov55** [comment]
I’m getting all of these errors upon starting the bot.py script
Is it a problem for sound?

ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
Sent from Mail for Windows 10

**Comment by rachnov55** [comment]
Again I’m getting it hearing what I’m saying but no reply

Google Speech Recognition thinks you said what time is it
Found face
I'm listening


Sent from Mail for Windows 10

**Comment by aak2003** [comment]
Check this line
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition
'cards.bcm2835_alsa.pcm.front.0:CARD=0'

I feel it says that there is a problem with the sound card

And for checking the virtual environment between the three folders just try
to activate bot.py in the terminal

**Comment by aak2003** [comment]
In the terminal be an administrator

**Comment by rachnov55** [comment]
Pcm card 0 is the native sound output…I’m using card 1 which is the USB sound blaster

This is driving me nuts!

Sent from Mail for Windows 10

**Comment by rachnov55** [comment]
How do I configure it to recognize my input is coming from usb card and to output to same card?  I have my usb sound card selected as default in settings.

Also, running python bot.py, it shows a message about unable to connect to server. Could this be the problem?
Sent from Mail for Windows 10

**Comment by aak2003** [comment]
See if it doesn't connect to the server that means the connectivity is not
good and if it doesn't connect to the server it cannot receive the data you
ask for

If the sound card is set to default then there is no problem to be with it
But still if you feel sound is a problem then attach a different source of
sound
