### ISSUE TITLE
trying to launch error

### ISSUE THREAD

**Issue by cowboysdude** [raghavpatnecha/smartmirror#2]
Warning: OpenCV not installed. To use facial recognition, make sure you've properly configured OpenCV.
HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /microphone?enabled=False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff7334de890>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "bot.py", line 679, in <module>
    bot.start()
  File "bot.py", line 49, in start
    requests.get("http://localhost:8090/clear")
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /clear (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff7334de8d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by cowboysdude** [comment]
HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /microphone?enabled=False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a756c890>: Failed to establish a new connection: [Errno 111] Connection refused',))
Found face
Traceback (most recent call last):
  File "bot.py", line 679, in <module>
    bot.start()
  File "bot.py", line 53, in start
    recognizer, audio = self.speech.listen_for_audio()
  File "/home/cowboysdude/Smart_Mirror/speech.py", line 33, in listen_for_audio
    m = sr.Microphone()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 113, in get_pyaudio
    raise AttributeError("PyAudio 0.2.11 or later is required (found version {})".format(pyaudio.__version__))
AttributeError: PyAudio 0.2.11 or later is required (found version 0.2.8)

**Comment by cowboysdude** [comment]
PyAudio 0.2.11 is installed......
still getting this error

**Comment by raghavpatnecha** [comment]
post the output of the following code
python -c 'import speech_recognition as sr; print(sr.Microphone.list_microphone_names())'

**Comment by raghavpatnecha** [comment]
Also I suggest you to do this again:
pip install -r requirements.txt
pip install --global-option='build_ext' --global-option='-I/usr/local/include' --global-option='-L/usr/local/lib' pyaudio

**Comment by cowboysdude** [comment]
Requirement already satisfied: pyaudio in /usr/local/lib/python2.7/dist-packages

Also I continue to get the 8080 error even though I have changed all the ports to 8090 in the bot.py......

As for the output of python -c 'import speech_recognition as sr; print(sr.Microphone.list_microphone_names())'

 python -c 'import speech_recognition as sr; print(sr.Microphone.list_microphone_names())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 123, in list_microphone_names
    audio = Microphone.get_pyaudio().PyAudio()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 113, in get_pyaudio
    raise AttributeError("PyAudio 0.2.11 or later is required (found version {})".format(pyaudio.__version__))
AttributeError: PyAudio 0.2.11 or later is required (found version 0.2.8)

**Comment by raghavpatnecha** [comment]
try this to check version. Sometimes it happen. Also, clear the cache
import speech_recognition as sr;print(sr.__version__)
import pyaudio as p;print(p.__version__)

**Comment by cowboysdude** [comment]
try this to check version. Sometimes it happen. Also, clear the cache
import speech_recognition as sr;print(sr.version)
import pyaudio as p;print(p.version)

Neither of those commands work....... 
bash: syntax error near unexpected token `p.version'
bash: syntax error near unexpected token `sr.version'

**Comment by cowboysdude** [comment]
Warning: OpenCV not installed. To use facial recognition, make sure you've properly configured OpenCV.
Used wrong endpoint for microphone debugging
Found face
Traceback (most recent call last):
  File "bot.py", line 679, in <module>
    bot.start()
  File "bot.py", line 53, in start
    recognizer, audio = self.speech.listen_for_audio()
  File "/home/cowboysdude/smartmirror/speech.py", line 33, in listen_for_audio
    m = sr.Microphone()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 113, in get_pyaudio
    raise AttributeError("PyAudio 0.2.11 or later is required (found version {})".format(pyaudio.__version__))
AttributeError: PyAudio 0.2.11 or later is required (found version 0.2.8)

**Comment by raghavpatnecha** [comment]
I couldn't understand the exact issue which is causing the error. So lets try few commands:
sudo apt-get install portaudio19-dev
sudo apt-get install python-pyaudio
sudo apt-get install libjack-jackd2-dev portaudio19-dev
brew install ffmpeg
also try to install alsa.lib 
update brew

Atleast something should work. Hit and try

**Comment by cowboysdude** [comment]
Used wrong endpoint for microphone debugging
Found face
Traceback (most recent call last):
  File "bot.py", line 679, in <module>
    bot.start()
  File "bot.py", line 53, in start
    recognizer, audio = self.speech.listen_for_audio()
  File "/home/cowboysdude/smartmirror/speech.py", line 33, in listen_for_audio
    m = sr.Microphone()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 113, in get_pyaudio
    raise AttributeError("PyAudio 0.2.11 or later is required (found version {})".format(pyaudio.__version__))
AttributeError: PyAudio 0.2.11 or later is required (found version 0.2.8)

**Comment by cowboysdude** [comment]
For the record I do in fact have 0.2.11 installed and why it's not recognizing that is beyond me......

**Comment by raghavpatnecha** [comment]
python -m speech_recognition try this . This error is beyond the scope of my knowledge. For me it just worked what we can do is try some methods. Also do check your pyaudio version manually before running the code. 
Also try this pip install pocketsphinx

**Comment by cowboysdude** [comment]
It continues to tell me I don't have pyaudio 0.2.11 installed and will not install it.  Tells me I have the latest version 0.2.8

Not sure but it seems to be an issue for others as well not just your package but many other people trying to use the newest pyaudio.......

**Comment by cowboysdude** [comment]
Yeah NOW I'm not happy.  My stable version of MM now automatically starts and I cannot kill it.  So my system is totally screwed up now......Sorry I'm done with this.

**Comment by cowboysdude** [comment]
Hahahahhahaha told you all on the forum that this wouldn't work....... I was right.
